### ISSUE TITLE
MIT

### ISSUE THREAD

**Issue by nanjizal** [FuzzyWuzzie/headbutt#1]
Would like the core under MIT licence? Could you consider splitting examples tests into other repositories?

**Comment by hamaluik** [comment]
Nope, my code is generally always licensed as Apache 2. It is still extremely permissive, with the addition over MIT of requiring you to state any changes you make to the code, protecting the name of the code, and protecting against patent trolls. Not that I expect this to ever get popular enough to need any of that, but I think it's the most fair & permissive open source license available.

Why would I split the samples and and tests into a different repository? They are specific to this codebase, so they should stay with the codebase. They also hardly clutter the repository.

**Comment by nanjizal** [comment]
Well the examples use three, was thinking it might be interesting to try a Kha example, to me three is just externs and js specific so does not really highlight the power of such libraries in Haxe.  If the examples are in another repository or abstracted out then the core would be added to haxelib to just be relevant algorithms, and have examples only on git to help with usage.  For instance that's the way I went with hxSpiro, it means the library does not assume too much about it's haxe visual use, also trying with a few approaches will help check it's flexibility.  I used to license BSD-2 but seems many haxelibs are MIT and the people who seem to need Apache2 are Adobe, Fb and corporations who halfheartedly go into opensource but maybe your reasoning is good.  It's just a bit nightmare with so many licenses around thought MIT was becoming common in haxe ecosystem.  hxSpiro license I am not happy with but had to respect the original authors intentions although how uses should treat the patent I made quite clear as europeans don't do software patents.

**Comment by hamaluik** [comment]
Ahh, the library doesn't require JS or three.js or anything. The samples are for showing it in use, and for this repo they're largely for the demos in my blog posts (ex: http://hamaluik.com/posts/building-a-collision-engine-part-3-3d-gjk-collision-detection/#demo). Unfortunately, to actually show anything useful each sample is like 95% "other code", and only a couple lines showing the library in action.

When I 1.0 the library I'll make sure there are more samples (including standalone, Kha, Luxe, OpenFL, etc)—for now I'm focused on getting the base functionality to work.

Yea, most Haxelibs are MIT but I don't think MIT gives enough protections to open source, and Haxe is definitely compatible with Apache2. Many companies use Apache2 when dealing with open source because they have to by the nature of doing business (protecting trademarks and patents, which MIT does not, and including legal specificity). I get that Haxe is largely European and things may differ over there, but where I am Apache2 just makes sense.
